# Generated by Django 5.2.7 on 2025-12-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_producto_precio_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='devolucionaproveedor',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=10, verbose_name='Estado'),
        ),
    ]
