# Generated by Django 5.2.7 on 2025-12-05 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_devolucionaproveedor_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devolucionaproveedor',
            options={'ordering': ['-fecha'], 'verbose_name_plural': 'Devoluciones a Proveedores'},
        ),
        migrations.RemoveField(
            model_name='devolucionaproveedor',
            name='total_devuelto',
        ),
        migrations.AddField(
            model_name='devolucionaproveedor',
            name='motivo',
            field=models.TextField(blank=True, max_length=500, verbose_name='Motivo'),
        ),
        migrations.AddField(
            model_name='devolucionaproveedor',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Devuelto'),
        ),
        migrations.AlterField(
            model_name='devolucionaproveedor',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESADA', 'Procesada'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='devolucionaproveedordetalle',
            name='devolucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='gestion.devolucionaproveedor'),
        ),
        migrations.AlterUniqueTogether(
            name='devolucionaproveedordetalle',
            unique_together={('devolucion', 'producto')},
        ),
    ]
