# Generated by Django 5.2.7 on 2025-10-31 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_ajustetipo_ajuste_ajustedetalle_cotizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.IntegerField(default=5, verbose_name='Stock Mínimo de Alerta'),
        ),
    ]
