# Generated by Django 5.2.7 on 2025-11-02 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_producto_stock_minimo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallecompra',
            old_name='precio_unitario',
            new_name='precio_compra',
        ),
    ]
