# Generated by Django 5.2.7 on 2025-11-26 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_rename_precio_unitario_detallecompra_precio_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ajustedetalle',
            name='tipo_ajuste',
        ),
        migrations.AddField(
            model_name='ajuste',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('PROCESADO', 'PROCESADO')], default='Pendiente', max_length=50),
        ),
        migrations.AddField(
            model_name='ajuste',
            name='tipo_ajuste',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='gestion.ajustetipo', verbose_name='Tipo de Ajuste General'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedidoclienteventa',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.pedidocliente'),
        ),
        migrations.AlterField(
            model_name='pedidoclienteventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.venta'),
        ),
    ]
