# Generated by Django 5.2.7 on 2025-12-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_remove_ajustedetalle_tipo_ajuste_ajuste_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ajuste',
            name='motivo_general',
        ),
        migrations.AddField(
            model_name='ajuste',
            name='motivo',
            field=models.TextField(default=1, verbose_name='Motivo General'),
            preserve_default=False,
        ),
    ]
