# Generated by Django 5.2.7 on 2025-10-19 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_departamento_marca_moneda_auditoria_caja_arqueo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('es_entrada', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Ajuste de Inventario',
            },
        ),
        migrations.CreateModel(
            name='Ajuste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('motivo_general', models.TextField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.empleado')),
            ],
            options={
                'verbose_name_plural': 'Ajustes de Inventario',
            },
        ),
        migrations.CreateModel(
            name='AjusteDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('observaciones', models.TextField(blank=True)),
                ('ajuste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.ajuste')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.producto')),
                ('tipo_ajuste', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.ajustetipo')),
            ],
            options={
                'verbose_name_plural': 'Detalles de Ajuste',
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_validez', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('Abierta', 'Abierta'), ('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada')], default='Abierta', max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.cliente')),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.empleado')),
            ],
            options={
                'verbose_name_plural': 'Cotizaciones',
            },
        ),
        migrations.CreateModel(
            name='CobroCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.metodopago')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.cotizacion')),
            ],
            options={
                'verbose_name_plural': 'Cobros de Cotización',
            },
        ),
        migrations.CreateModel(
            name='CotizacionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.cotizacion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.producto')),
            ],
            options={
                'verbose_name_plural': 'Detalles de Cotización',
            },
        ),
        migrations.CreateModel(
            name='DevolucionAProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total_devuelto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('compra_original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.compra')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.proveedor')),
            ],
            options={
                'verbose_name_plural': 'Devoluciones a Proveedores',
            },
        ),
        migrations.CreateModel(
            name='DevolucionAProveedorDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_devuelto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.devolucionaproveedor')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.producto')),
            ],
            options={
                'verbose_name_plural': 'Detalles de Devolución a Proveedor',
            },
        ),
        migrations.CreateModel(
            name='OrdenDePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_orden', models.DateTimeField(auto_now_add=True)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagada', 'Pagada'), ('Anulada', 'Anulada')], default='Pendiente', max_length=50)),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.empleado')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.moneda')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.proveedor')),
            ],
            options={
                'verbose_name_plural': 'Órdenes de Pago',
            },
        ),
        migrations.CreateModel(
            name='OrdenDePagoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_aplicado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cuenta_a_pagar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.cuentaapagar')),
                ('orden_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.ordendepago')),
            ],
            options={
                'verbose_name_plural': 'Detalles de Orden de Pago',
            },
        ),
        migrations.CreateModel(
            name='PedidoAProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('fecha_recepcion_estimada', models.DateField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Recibido', 'Recibido'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=50)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.empleado')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.proveedor')),
            ],
            options={
                'verbose_name_plural': 'Pedidos a Proveedores',
            },
        ),
        migrations.CreateModel(
            name='PedidoAProveedorDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_acordado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.pedidoaproveedor')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.producto')),
            ],
            options={
                'verbose_name_plural': 'Detalles de Pedido a Proveedor',
            },
        ),
        migrations.CreateModel(
            name='PedidoClienteVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_relacion', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.pedidocliente')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.venta')),
            ],
            options={
                'verbose_name': 'Relación Pedido-Venta',
                'verbose_name_plural': 'Relaciones Pedido-Venta',
                'unique_together': {('pedido', 'venta')},
            },
        ),
        migrations.CreateModel(
            name='PresupuestoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_relacion', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.pedidocliente')),
                ('presupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.presupuesto')),
            ],
            options={
                'verbose_name': 'Relación Presupuesto-Pedido',
                'verbose_name_plural': 'Relaciones Presupuesto-Pedido',
                'unique_together': {('presupuesto', 'pedido')},
            },
        ),
    ]
